export const GIG_CATEGORIES = [
  { id: 'plumber', label: 'Plumber', icon: '🔧' },
  { id: 'electrician', label: 'Electrician', icon: '⚡' },
  { id: 'cleaner', label: 'Cleaner', icon: '🧹' },
  { id: 'mechanic', label: 'Mechanic', icon: '🔩' },
  { id: 'nurse', label: 'Nurse / Caregiver', icon: '🏥' },
  { id: 'babysitter', label: 'Babysitter', icon: '👶' },
  { id: 'painter', label: 'Painter', icon: '🎨' },
  { id: 'carpenter', label: 'Carpenter', icon: '🪚' },
  { id: 'landscaper', label: 'Landscaper', icon: '🌿' },
  { id: 'mover', label: 'Mover', icon: '📦' },
  { id: 'tutor', label: 'Tutor', icon: '📚' },
  { id: 'photographer', label: 'Photographer', icon: '📷' },
  { id: 'chef', label: 'Chef / Caterer', icon: '👨‍🍳' },
  { id: 'personal_trainer', label: 'Personal Trainer', icon: '💪' },
  { id: 'delivery', label: 'Delivery / Driver', icon: '🚗' },
  { id: 'pet_care', label: 'Pet Care', icon: '🐾' },
  { id: 'handyman', label: 'Handyman', icon: '🛠️' },
  { id: 'hvac', label: 'HVAC Technician', icon: '❄️' },
  { id: 'other_gig', label: 'Other', icon: '⚙️' },
];

export const PROFESSIONAL_CATEGORIES = [
  { id: 'technology', label: 'Technology', icon: '💻' },
  { id: 'finance', label: 'Finance & Accounting', icon: '💰' },
  { id: 'healthcare', label: 'Healthcare & Medical', icon: '🏥' },
  { id: 'legal', label: 'Legal', icon: '⚖️' },
  { id: 'engineering', label: 'Engineering', icon: '⚙️' },
  { id: 'marketing', label: 'Marketing & Sales', icon: '📣' },
  { id: 'design', label: 'Design & Creative', icon: '🎨' },
  { id: 'education', label: 'Education', icon: '🎓' },
  { id: 'hr', label: 'Human Resources', icon: '👥' },
  { id: 'management', label: 'Management & Operations', icon: '📊' },
  { id: 'construction', label: 'Construction & Architecture', icon: '🏗️' },
  { id: 'real_estate', label: 'Real Estate', icon: '🏠' },
  { id: 'logistics', label: 'Logistics & Supply Chain', icon: '🚚' },
  { id: 'customer_service', label: 'Customer Service', icon: '🎧' },
  { id: 'writing', label: 'Writing & Content', icon: '✍️' },
  { id: 'other_pro', label: 'Other', icon: '💼' },
];

export const US_STATES = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
  'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
  'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
  'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
  'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
  'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
  'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
  'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
  'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
  'West Virginia', 'Wisconsin', 'Wyoming',
];
